name: Update tags data
on:
  schedule:
    - cron: '0 0 */1 * *'
  push:

permissions:
  contents: write
  
jobs:
  Update_tags_data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        node-version: 18
    
    - run: npm install
    - run: npm run start
    - uses: EndBug/add-and-commit@v9
      with:
        message: 'Update .json files'
        add: '*.json'
        cwd: '/docs/'
